//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVotingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voter()
        {
            this.VoteCastingInformations = new HashSet<VoteCastingInformation>();
        }
    
        public int VoterId { get; set; }
        public string Name { get; set; }
        public string ServiceId { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public bool IsCommittedVote { get; set; }
        public Nullable<System.Guid> UniqueIdentification { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoteCastingInformation> VoteCastingInformations { get; set; }
    }
}
